# Generated by Django 4.2.1 on 2023-08-30 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referredby',
            name='referredByUser',
        ),
        migrations.AlterField(
            model_name='referredby',
            name='referredToUser',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='referredby',
            name='referredByUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
