# Generated by Django 4.2.1 on 2023-09-02 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountSent', models.IntegerField()),
                ('rewardAmountToSender', models.IntegerField()),
                ('confirmed', models.BooleanField()),
                ('transacBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('transacTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toSend', models.IntegerField()),
                ('receiverUPI', models.BigIntegerField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pairs', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ManyToManyField(related_name='sent_pairs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='transactionControl.transaction')),
            ],
        ),
    ]
