# Generated by Django 4.2.1 on 2023-09-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionControl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed',
        ),
    ]
