# Generated by Django 4.2.1 on 2023-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionControl', '0002_remove_transaction_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default='2023-09-02 11:11:00'),
        ),
    ]
