# Generated by Django 4.2.1 on 2023-09-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionControl', '0003_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateField(default='2023-09-02'),
        ),
    ]
