# Generated by Django 4.2.1 on 2023-09-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionControl', '0004_alter_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='receiverUPI',
            field=models.BigIntegerField(null=True),
        ),
    ]
